language: android
dist: trusty

env:
  global:
  - ANDROID_API_LEVEL=29
  - ANDROID_BUILD_TOOLS_VERSION=29.0.2
  - ANDROID_EMU_API_LEVEL=22
  - ANDROID_ABI=armeabi-v7a
  # - ANDROID_ABI=x86_64
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMU_API_LEVEL
    - extra
    - add-on
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-android-support
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - addon-google_apis-google-$EMULATOR_API_LEVEL
    # - sys-img-$ANDROID_ABI-addon-google_apis-google-$ANDROID_API_LEVEL
    # - sys-img-$ANDROID_ABI-addon-google_apis-google-$EMULATOR_API_LEVEL
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL
    #- sys-img-x86-android-ANDROID_API_LEVEL

  licenses:
    - 'android-sdk-license-.+'
    
before_install:
# - yes | sdkmanager --licenses
- chmod +x gradlew
- android list target



before_script:
  # - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi addon-google_apis-$ANDROID_ABI
  - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi  google_apis/$ANDROID_ABI -c 10M
  # - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI -c 100M
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  # - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace --warning-mode all
  - ./gradlew build
  # - ./gradlew connectedCheck