language: android
dist: trusty

env:
  global:
  - ANDROID_API_LEVEL=29
  - ANDROID_BUILD_TOOLS_VERSION=29.0.2
  - ANDROID_EMU_API_LEVEL=25
  - ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - tools
    - extra
    - addon
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMU_API_LEVEL
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL
    #- sys-img-x86-android-29

  licenses:
    - 'android-sdk-license-.+'
    
before_install:
# - yes | sdkmanager "platforms;android-29"
- chmod +x gradlew
- android list target



before_script:
  - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI -c 100M
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace --warning-mode all
  # - ./gradlew build
  # - ./gradlew connectedCheck