language: android
dist: trusty

env:
  global:
  - ANDROID_API_LEVEL=26
  - ANDROID_BUILD_TOOLS_VERSION=26.0.1
  - ANDROID_EMU_API_LEVEL=22
  - ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - tools
    - platform-tools
    - extra
    - addon
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL
    #- sys-img-x86-android-29
    
before_install:
- yes | sdkmanager "platforms;android-26"
- chmod +x gradlew

# before_script:
  # - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI
  # - emulator -avd test -no-window &
  # - android-wait-for-emulator
  # - adb shell input keyevent 82 &

script:
  - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace --warning-mode all